[spell]
lang = "ja-JP"  # "en-US" for English, "ja-JP" for Japanese
threshold = 0.3  # acceptable error-rate for speech recognition
commands = [
  # hair style
  {spell = "金髪", dest = "/avatar/parameters/hair", args=[0.0]},
  {spell = "white hair", dest = "/avatar/parameters/hair", args=[0.0]},
  {spell = "金髪ツイン", dest = "/avatar/parameters/hair", args=[0.4]},
  {spell = "twin white hair", dest = "/avatar/parameters/hair", args=[0.4]},
  {spell = "white twin hair", dest = "/avatar/parameters/hair", args=[0.4]},
  {spell = "金髪ショート", dest = "/avatar/parameters/hair", args=[0.7]},
  {spell = "short white hair", dest = "/avatar/parameters/hair", args=[0.7]},
  {spell = "white short hair", dest = "/avatar/parameters/hair", args=[0.7]},

  {spell = "黒髪", dest = "/avatar/parameters/hair", args=[0.2]},
  {spell = "black hair", dest = "/avatar/parameters/hair", args=[0.2]},
  {spell = "黒髪ショート", dest = "/avatar/parameters/hair", args=[0.9]},
  {spell = "short black hair", dest = "/avatar/parameters/hair", args=[0.9]},
  {spell = "black short hair", dest = "/avatar/parameters/hair", args=[0.9]},
  {spell = "黒髪ツイン", dest = "/avatar/parameters/hair", args=[0.6]},
  {spell = "twin black hair", dest = "/avatar/parameters/hair", args=[0.6]},
  {spell = "black twin hair", dest = "/avatar/parameters/hair", args=[0.6]},

  {spell = "茶髪", dest = "/avatar/parameters/hair", args=[0.3]},

  # hand
  {spell = "猫の手", dest = "/avatar/parameters/TE", args=[1]},
  {spell = "人の手", dest = "/avatar/parameters/TE", args=[0]},

  # AFK
  {spell = "退席", dest = "/avatar/parameters/AFK", args=[1]},
  {spell = "体積", dest = "/avatar/parameters/AFK", args=[1]},
  {spell = "戻ってきた", dest = "/avatar/parameters/AFK", args=[0]},

  # earring
  {spell = "右耳 なし", dest = "/avatar/parameters/rightear", args=[0]},
  {spell = "右耳 ウェーブ", dest = "/avatar/parameters/rightear", args=[1]},
  {spell = "右耳 鎖", dest = "/avatar/parameters/rightear", args=[2]},
  {spell = "右耳 十字架", dest = "/avatar/parameters/rightear", args=3},
  {spell = "右耳 ダイヤモンド", dest = "/avatar/parameters/rightear", args=[4]},
  {spell = "左耳 なし", dest = "/avatar/parameters/leftear", args=[0]},
  {spell = "左耳 ウェーブ", dest = "/avatar/parameters/leftear", args=[1]},
  {spell = "左耳 鎖", dest = "/avatar/parameters/leftear", args=[2]},
  {spell = "左耳 十字架", dest = "/avatar/parameters/leftear", args=[3]},
  {spell = "左耳 ダイヤモンド", dest = "/avatar/parameters/leftear", args=[4]},

  # costume
  {spell = "メイド服", dest = "/avatar/parameters/Costume", args=[0]},
  {spell = "学生服", dest = "/avatar/parameters/Costume", args=[1]},
  {spell = "パジャマ", dest = "/avatar/parameters/Costume", args=[2]},
  {spell = "ワンピース", dest = "/avatar/parameters/Costume", args=[3]},
  {spell = "ONE PIECE", dest = "/avatar/parameters/Costume", args=[3]},
  {spell = "ロングワンピース", dest = "/avatar/parameters/Costume", args=[3]},

  # head accessory
  {spell = "頭なし", dest = "/avatar/parameters/HeadCostume", args=[0]},
  {spell = "リボン", dest = "/avatar/parameters/HeadCostume", args=[1]},
  {spell = "頭 ドレス", dest = "/avatar/parameters/HeadCostume", args=[2]},

  # PPPen
  {spell = "ペンを使う", dest = "/avatar/parameters/PPPen_Write", args=[1]},
  {spell = "ペンで書く", dest = "/avatar/parameters/PPPen_Write", args=[1]},
  {spell = "ペンを取り出す", dest = "/avatar/parameters/PPPen_Write", args=[1]},
  {spell = "ペンをしまう", dest = "/avatar/parameters/PPPen_Write", args=[0]},

]

[vrchat]
send_port = 9000
recv_port = 9001
host = "$WIN"  # "$WIN": Windows port from WSL, "localhost" or IP "000.000.000.000"
