[spell]
lang = "ja-JP"  # "en-US" for English, "ja-JP" for Japanese
translate = true  # true or false, enable to translate
translate_langs = ["en", "zh", "ko"]  # to these langs

threshold = 0.3  # acceptable error-rate for speech recognition
commands = [
  # Magic command for free-textchat
  {spell = "start to chat", dest = "/textchat/start", args=[]},
  {spell = "end to chat", dest = "/textchat/end", args=[]},
  {spell = "話す", dest = "/textchat/start", args=[]},
  {spell = "終わり", dest = "/textchat/end", args=[]},
  {spell = "終わる", dest = "/textchat/end", args=[]},

  # Avatar Parameters (Sample)
  {spell = "Dress A", dest = "/avatar/parameters/dress", args=[0]},
  {spell = "Dress B", dest = "/avatar/parameters/dress", args=[1]},
]

[vrchat]
send_port = 9000
recv_port = 9001

# hostname or IP of the machine running VRChat
# If you are on WSL2 (not docker) and VRChat running on Windows host, you can use "$WIN"
host = "192.168.10.10"
