[spell]
lang = "en-US"  # "en-US" for English. Only en-US is supported now.
threshold = 0.3  # acceptable error-rate for speech recognition
commands = [
  {spell = "white hair", dest = "/avatar/parameters/hair", args=[0.0]},
  {spell = "twin white hair", dest = "/avatar/parameters/hair", args=[0.4]},
  {spell = "white twin hair", dest = "/avatar/parameters/hair", args=[0.4]},
  {spell = "short white hair", dest = "/avatar/parameters/hair", args=[0.7]},
  {spell = "white short hair", dest = "/avatar/parameters/hair", args=[0.7]},

  {spell = "black hair", dest = "/avatar/parameters/hair", args=[0.2]},
  {spell = "short black hair", dest = "/avatar/parameters/hair", args=[0.9]},
  {spell = "black short hair", dest = "/avatar/parameters/hair", args=[0.9]},
  {spell = "twin black hair", dest = "/avatar/parameters/hair", args=[0.6]},
  {spell = "black twin hair", dest = "/avatar/parameters/hair", args=[0.6]},

  {spell = "brown hair", dest = "/avatar/parameters/hair", args=[0.3]},
]

[vrchat]
send_port = 9000
recv_port = 9001
host = "$WIN"  # "$WIN": Windows port from WSL, "localhost" or IP "000.000.000.000"
